apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swarm.fullname" . }}-mission
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "swarm.labels" . | nindent 4 }}
data:
  swarm_mission.json: {{ .Values.missionConfig | quote }}
