{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "swarm.fullname" . }}-quota
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "swarm.labels" . | nindent 4 }}
spec:
  hard:
    pods: {{ .Values.resourceQuota.maxPods | quote }}
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
{{- end }}
